test:
  workers:
    number: 5
  rounds:
    - label: Create a prescription.
      # 5000 transactions should create around 1000 prescription per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 500
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/createPrescription.js
    - label: Read a prescription.
      # 5000 transactions should create around 1000 prescription per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 500
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/readPrescription.js