test:
  workers:
    number: 5
  rounds:
    - label: Create a prescription.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/createPrescription.js
    - label: Read a prescription.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/readPrescription.js
    - label: Share a prescription.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/sharePrescription.js
    - label: Update a prescription.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/updatePrescription.js
    - label: Setfill a prescription.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/setfillPrescription.js
    - label: Read a report.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/basicb64/readReport.js