test:
  workers:
    number: 5
  rounds:
    - label: Register a report reader.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/rsa/addReader.js
    - label: Update a prescription to a report.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/rsa/updateReport.js
    - label: Read a report.
      txNumber: 100
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: benchmarks/rsa/readReport.js